### ISSUE TITLE
Changing default branch from Master to Main while still keeping the master 

### ISSUE THREAD

**Issue by Dhruv-Sachdev1313** [badging/event-diversity-and-inclusion#119]
We can make a new branch as `Main` and make it the default branch and still keep the `Master` branch for some time so that it doesn't break anything. Then maybe delete the `Master` after some time. 
This is how @sgoggins made the change to `Main` for Augur!

**Comment by ElizabethN** [comment]
@Nebrethar @kaxada I think this is a super important change to make. Can I make it? Will it mess up the Badging Bot if I do?

**Comment by ayushtamra** [comment]
Yes, I think its implementable with probably not breaking anything(because the implementation is not much dependent on branch) but making things sure enough we have decided to make the bot use .md files which is in the .github directory from the badging-bot repository ,i.e, migrating the .github folder to the badging bot project directory and accessing the welcome messages and checklist messages from there.
This will replace the implementation of accessing repository contents through Github API and then changing branch will not effect it.

You can find the links here:

Project idea: https://github.com/orgs/badging/projects/1#card-79627246
Issue: https://github.com/badging/badging-bot/issues/9

Its implemented  with this [pull-request](https://github.com/badging/badging-bot/pull/3) and with support of @Nebrethar I think we will be deploying it soon, in the next versions of it.

**Comment by Nebrethar** [comment]
This will have to happen upon the next release of the badging-bot 😁 see you soon!

**Comment by ElizabethN** [comment]
@kaxada do you think this is something we could prioritize with upcoming releases? I'd really love to see this happen but I'm not sure what it will take to get it there 🤔 Do you have thoughts on this?

**Comment by ElizabethN** [comment]
Just wanted to bump this up because i think it's super important to do. I am not sure what it will require though! cc @kaxada

**Comment by kaxada** [comment]
Ohh. As far as I know. the related configurations between this and other repositories are not affected by the naming of the branch. So we can make the change now. let me do it.

**Comment by kaxada** [comment]
to change the name of your local branch copy and paste this:
```sh
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
