### ISSUE TITLE
Google Summer of Code Idea: Badging Bot

### ISSUE THREAD

**Issue by Nebrethar** [badging/event-diversity-and-inclusion#134]
## From the [GSOC Ideas Document ](https://github.com/chaoss/community/edit/main/GSoC-Ideas.md)
 The CHAOSS DEI Badging Initiative has been providing badges to event organizers who implement valid DEI practices into their events. The badge is used as a reward system for events with inclusive and welcoming environments. In each review, the Badging Initiative uses a badging-bot to automate some of the processes that help an applicant earn their event badge.
 The idea of this mentorship is to learn about CHAOSS DEI Badging and its badging bot, then improve the processes and operation of the badging-bot. This may include working on learning the existing code as well as with algorithms and cross-file references in Javascript. The GSoC student may also be expected to deploy the improvements to the bot on GitHub.

The aims of the project are as follows:
  - Clean up and document current badging-bot code and processes
  - Migrate the badging-bot to a new platform
  - Time permitting, integrate a reviewer assignment algorithm

The applicant must be prepared to work with existing code to improve a GitHub app and integrate that app into the repositories for the CHAOSS Badging Initiative

* _Difficulty:_ Medium
* _Requirements:_ Appreciates DEI, Working knowledge of JavaScript, Experience with GitHub Apps
* _Recommended:_ Experience with webhooks, Experience creating documentation
* _Mentors:_ Matt Germonprez

### Microtask 1: Submit a phony badge application
 - Submit an event badge application using your (made-up) info on the [CHAOSS web](https://chaoss.community/diversity-and-inclusion-badging/) form. Make sure you actually submit the GitHub issue.
 - Report back in a comment on this issue with what you found, and how the process could be improved.

### Microtask 2: Provide a GitHub App Concept - Updated 3/7/2022
 - Review the (Official GitHub Documentation)[https://docs.github.com/en/developers/apps/getting-started-with-apps/about-apps] on GitHub Apps.
 - Come up with an idea for your own GitHub app. Any idea will do!
 - Describe, with 3-5 bullet points, the major steps you would take to install the GitHub App.

**Comment by ayushtamra** [comment]
Hello @Nebrethar 
My name is Ayush and I am an undergraduate student from India. I am really interested to work on this idea in GSOC, currently I am learning about the Github webhooks and learning how can I deploy a Github app, and I want to be an active contributor in this project.
The DEI is something which I personally feel is very important in tech and opensource and it inclines towards my personal interests to make tech an inclusive place.
I will be grateful to you, if you could guide me regarding this, thank you!

**Comment by germonprez** [comment]
Hi @ayushtamra are you able to follow the microtasks? I think that might be a good place to start.

**Comment by ayushtamra** [comment]
**Microtask 1: Submit a phony badge application**

> Reference: Report back in a comment on this issue with what you found, and how the process could be improved.

Hello!
My experience of applying for badging process was really great and easy, however I feel there may be some improvements we can make in the process to make a great badging process experience for the applicants,

**Improving the application form**

The application form from a UI/UX perspective, can be improved with a good user interface, the first idea that comes into my mind is to improve the current implementation and the second one is by accomplishing some form integration services example: [typeform](https://www.typeform.com/).

Some other issues in the form that applicants might face:

* Its not possible for the applicant to go back and edit the details(if they want to) in the form after clicking the submit button, the only option remains is to edit the markdown result, which may be very difficult for some applicants who are not much familiar with markdown, so we can improve the webpage implementation for this particular part.

We can also skip a step where applicants have to copy the markdown code and paste it in the application github issue: 
In place of this we can use a Github [Issue forms](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms) feature, which can be used directly as an form template on github issue for the application, this is a beta feature of issue templates but works quite smoothly.

* The reviewer assignment by the bot is also a problem currently, as mentioned in the project idea too. This is probably a good improvement to work on, this may take some time for improvement but in the meantime we can just improve the bot to tag some set of reviewers or maintainers, so that they get notified for it and they can further assign this to reviewers.

**Comment by ayushtamra** [comment]
Hello @germonprez @Nebrethar 
I have submitted my proposal and my microtasks, with this [pr](https://github.com/chaoss/community/pull/355)

My microtasks: https://docs.google.com/document/d/1EGBfgwb7iJHlGnrq6l0-dQrpHW92gxArkP6BxG4W-qE/edit?usp=sharing

My proposal: https://docs.google.com/document/d/1R0UKhAKr1OUzFsjvZmy2O1sreYv8KyMt5y_i-2w2tqk/edit?usp=sharing

Thank you so much✨

**Comment by ElizabethN** [comment]
I'm closing this since GSoC is over. Thanks everybody!
