### ISSUE TITLE
Attention! 3 New Metrics Being Added This Week - Badging 4.0!

### ISSUE THREAD

**Issue by ElizabethN** [badging/event-diversity-and-inclusion#333]
This is for event organizers who complete applications and for our team of @badging/reviewers. 

Last year we started on a journey to add 3 new metrics to our event application. It was put on hold for a while but we have brought this around again and are implementing these changes this week. 

Name | Question
--- | ---
[Event Accessibility](https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/event-accessibility.md) | To what extent does your event accommodate those with various accessibility needs?
[Event Location Inclusivity](https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/event-location-inclusivity.md) | Is the event located in a region where governments, cultural contexts, or society may cause harm to the physical safety and/or psychological safety of event attendees?
[Public Health and Safety](https://github.com/chaoss/wg-dei/blob/main/focus-areas/event-diversity/public-health-and-safety.md) | To what extent does your event address public health through policies around masks, vaccines, COVID testing, and in infrastructure such as ventilation and air purification in indoor venues?

@badging/reviewers - your checklist will look a little different than before. You will have 3 new metrics to consider. The questions are relatively straightforward, but if you need clarification on anything in the review, don't hesitate to ask. 

Event organizers (@mgoytia04, @andreacalderonlf, @sarah-coghlan, @mrsjent, @floord,@nicoleblessing, @plainschwartz, @mollyalexander, @csharpfritz, @nvibert, @stearnsbridget, @wendi-west, @rachelbraunlf and others):

- this will not affect any current or past applications
- next application you complete will ask you questions about these 3 new metrics
- Our process is still the same with regard to calculating badges. There will just be more checkmarks to achieve.
- if you have any questions at all, please don't hesitate to ask either in this issue, in our CHAOSS Slack channel, or via email at elizabeth@chaoss.community.  

Thanks everyone! 
I will leave this issue open for a bit so everyone has a chance to see it.

**Comment by csharpfritz** [comment]
It feels like not all of these apply to online events, am I right about that?On May 14, 2024, at 08:38, Elizabeth Barron ***@***.***> wrote:﻿[badging/event-diversity-and-inclusion] Attention! 3 New Metrics Being Added This Week - Badging 4.0! (Issue #333)This is for event organizers who complete applications and for our team of @badging/reviewers.Last year we started on a journey to add 3 new metrics to our event application. It was put on hold for a while but we have brought this around again and are implementing these changes this week.NameQuestionEvent AccessibilityTo what extent does your event accommodate those with various accessibility needs?Event Location InclusivityIs the event located in a region where governments, cultural contexts, or society may cause harm to the physical safety and/or psychological safety of event attendees?Public Health and SafetyTo what extent does your event address public health through policies around masks, vaccines, COVID testing, and in infrastructure such as ventilation and air purification in indoor ***@***.***/reviewers - your checklist will look a little different than before. You will have 3 new metrics to consider. The questions are relatively straightforward, but if you need clarification on anything in the review, don't hesitate to ask.Event organizers ***@***.***, @AndreaCalderonLF, @sarah-coghlan, @mrsjent, @***@***.***, @plainschwartz-team, @mollyalexander, @csharpfritz, @nvibert, @stearnsbridget, @Wendi-West, @RachelBraunLF and others):this will not affect any current or past applicationsnext application you complete will ask you questions about these 3 new metricsOur process is still the same with regard to calculating badges. There will just be more checkmarks to achieve.if you have any questions at all, please don't hesitate to ask either in this issue, in our CHAOSS Slack channel, or via email at ***@***.*** everyone!I will leave this issue open for a bit so everyone has a chance to see it.—Reply to this email directly, view it on GitHub or unsubscribe.You are receiving this email because you were mentioned.Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ElizabethN** [comment]
@csharpfritz - great question! For virtual events, the Event Accessibility metric will be applied (we'll ask you about closed captioning for online presentations, and the ability to accommodate any accessibility requests.)

Hope that helps!

**Comment by ElizabethN** [comment]
This has been implemented successfully, so I'm going to close this issue. Thanks everyone!
