### ISSUE TITLE
[Virtual Event] FOSS Backstage

### ISSUE THREAD

**Issue by Max-Plain-Schwarz** [badging/event-diversity-and-inclusion#59]
# Virtual Event Submission

## Requirements

- Event Name: FOSS Backstage
- Link to the Event Website: https://foss-backstage.de/
- Provide verification that you are an event organizer: If you send an email to info@foss-backstage.de I (Max King) will respond

## Speaker Demographics

- [x] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A`  Please follow the link to see the demographic survey we will be using for 2021 https://crumpet.webo.family/index.php/apps/forms/SNXgQT6gT3yx5oQX
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` This is the first year we are collecting this data, so we will display the data for FOSS Backstage 2021 after the event.

## Attendee Demographics

- [x] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` Please follow the link to see the demographic survey we will be using for 2021 https://crumpet.webo.family/index.php/apps/forms/SNXgQT6gT3yx5oQX
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` This is the first year we are collecting this data, so we will display the data for FOSS Backstage 2021 after the event.

## Code of Conduct at Event

- [x] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` FOSS Backstage 2021 will be an online event so the CoC can be found on our website through the link below. Attendees are asked to comply with the CoC before they can buy a ticket.
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://foss-backstage.de/code-conduct

## Diversity Access Tickets

- [x] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` We have one type of Diversity Access Ticket which provides a free ticket for the event.
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A`  Diversity Access Tickets are available to people from underrepresented groups within the FOSS community. This includes, but is not limited to: women, people of colour, LGBTQIA people, disabled people, and people facing economic or social hardships. We do not place any barriers to accessing these tickets, and access to these tickets is at the individual's digression. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  https://foss-backstage.de/diversity

**Comment by Nebrethar** [comment]
Thank you @Max-Plain-Schwarz for applying to our project on behalf of FOSS Backstage. 

😁 We are so glad you are here. Let me know if you have any questions.

**Comment by xiaoya-Esther** [comment]
Thanks for the Application! 🎉🎉🎉 Don't hesitate to pin in the issue if any questions come out.

**Comment by Ruth-ikegah** [comment]
# Event Review Checklist


## > Initial checks

- [x] Event is about Open Source technologies and systems.
- [x] Event information is publicly available on a website.
- [x] The Event Code of Conduct is publicly available.
- [x] The applicant is the organizer of the event.

💡 ``` Make sure all the initial checks are marked before proceeding with Metric based checks```

## > Metric based checks

### >> Speaker Demographics and Inclusivity
- [x] **Measuring demographics** - The Event has a process for measuring speaker demographics.
- [ ] **Displaying demographics** - The Event displays speaker demographics.
  - Ask applicant about the process if information is not openly available.

### >> Attendee Demographics and inclusivity
- [x] **Measuring Demographics** - The Event has a process for measuring Attendee demographics.
- [ ] **Displaying demographics** - The Event displays attendee demographics.
- [x] **Attendee Inclusivity** - The Event requests feedback from attendees regarding Diversity & Inclusion.
  - Ask applicant about the process if information is not openly available.

### >> Code of Conduct at Event
- [x] **Findability** - It is possible to find the Code of Conduct on the Event website.
- [x] **Clarity** - Event Code of Conduct provides a definition of expected behaviour.
- [x] **Reporting venue** - The event has a venue for reporting violations of the CoC at the event website.
- [ ] **Support at Event** - The Event Code of Conduct provided information about possible methods to provide support to victims of inappropriate behavior.
- [x] **Enforcement** - The participants in the Event are required to accept the Code of Conduct.
    

### >> Diversity Access tickets
- [x] **Availability** - The event provides one or more Diversity Access Tickets.
- [x] **Ticket allocation** - The Event has a process for allocating diversity access tickets.
- [x] **Findability** - The information about Diversity Access Tickets is public.

**Comment by Ruth-ikegah** [comment]
Thanks, @Max-Plain-Schwarz for applying for a badge!

**Comment by Max-Plain-Schwarz** [comment]
Thanks all for making this great project happen. We're really excited to be a part of it :)

**Comment by tetris4** [comment]
# Event Review Checklist

## > Initial checks

- [x] Event is about Open Source technologies and systems.
- [x] Event information is publicly available on a website.
- [x] The Event Code of Conduct is publicly available.
- [x] The applicant is the organizer of the event.

## > Metric based checks

### >> Speaker Demographics and Inclusivity
- [x] **Measuring demographics** - The Event has a process for measuring speaker demographics.
- [ ] **Displaying demographics** - The Event displays speaker demographics.

### >> Attendee Demographics and Inclusivity
- [x] **Measuring Demographics** - The Event has a process for measuring Attendee demographics.
- [ ] **Displaying demographics** - The Event displays attendee demographics.
- [x] **Attendee Inclusivity** - The Event requests feedback from attendees regarding Diversity & Inclusion.
  - Ask applicant about the process if information is not openly available.

### >> Code of Conduct at Event
- [x] **Findability** - It is possible to find the Code of Conduct on the Event website.
- [x] **Clarity** - Event Code of Conduct provides a definition of expected behaviour.
- [x] **Reporting venue** - The event has a venue for reporting violations of the CoC at the event website.
- [x] **Support at Event** - The Event Code of Conduct provided information about possible methods to provide support to victims of inappropriate behavior.
- [x] **Enforcement** - The participants in the Event are required to accept the Code of Conduct.

### >> Diversity Access tickets
- [x] **Availability** - The event provides one or more Diversity Access Tickets.
- [x] **Ticket allocation** - The Event has a process for allocating diversity access tickets.
- [x] **Findability** - The information about Diversity Access Tickets is public.

**Comment by tetris4** [comment]
Hi @Max-Plain-Schwarz, thank you for applying for a badge! As this is the first year you are collecting speaker & attendee data you obviously can't do anything on displaying them before the event, but you can possibly bump this evaluation post-event once you share it. You are at Gold badge anyway, with 11/13 items covered, so >80%. Have a great event, I look forward to it!

**Comment by Nebrethar** [comment]
Note: @xiaoya-Esther @germonprez

Looks like this application is ready. 😁 Please email me if you have any issues with the bot at this stage.

**Comment by Max-Plain-Schwarz** [comment]
Hi all, this is great to hear. What is the next stage? How do we share our badging?

**Comment by germonprez** [comment]
@Nebrethar what do you mean about issues with the bot? Like it keeps going or something =]

Thanks @tetris4 and @Ruth-ikegah for the reviews!

@Max-Plain-Schwarz I'll let @Nebrethar but I think at this point you should receive the the badge and we would also record it in the CHAOSS project.

**Comment by Nebrethar** [comment]
I think the bot is being worked on right now.. I will manually place the badge here and add it to the list :)

**Comment by Nebrethar** [comment]
Congratulations @Max-Plain-Schwarz on behalf of FOSS Backstage! This event has earned a CHAOSS GOLD badge. The event will now be added to the list in this project's README.

![Assigned badge: gold](https://img.shields.io/badge/D%26I-GOLD-yellow?logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJDSEFPU1NfTG9nbyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmlld0JveD0iMCAwIDI1NSAyNTUiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8cGF0aCBvcGFjaXR5PSIwLjUiIGQ9Ik05OS42LDYxLjhjMTgtNi43LDM3LjgtNi44LDU1LjktMC4yTDE3MywzMS40Yy0yOS0xMi4zLTYxLjgtMTIuMi05MC44LDAuM0w5OS42LDYxLjh6Ii8+CjxwYXRoIG9wYWNpdHk9IjAuNSIgZD0iTTE5Ny4xLDQ1LjNsLTE3LjUsMzAuMmMxNC44LDEyLjMsMjQuNywyOS41LDI3LjksNDguNWgzNC45QzIzOC43LDkyLjcsMjIyLjQsNjQuMiwxOTcuMSw0NS4zeiIvPgo8cGF0aCBvcGFjaXR5PSIwLjUiIGQ9Ik0yMDcuNCwxNTEuOWMtNy45LDQzLjktNDkuOSw3My05My44LDY1LjFjLTEzLjgtMi41LTI2LjgtOC42LTM3LjUtMTcuNmwtMjYuOCwyMi40CgljNDYuNiw0My40LDExOS41LDQwLjksMTYyLjktNS43YzE2LjUtMTcuNywyNy00MC4yLDMwLjEtNjQuMkgyMDcuNHoiLz4KPHBhdGggb3BhY2l0eT0iMC41IiBkPSJNNTguMSwxNzguMUMzOC40LDE0NC4zLDQ1LjgsMTAxLjMsNzUuNiw3Nkw1OC4yLDQ1LjdDMTAsODIuMy0xLjcsMTQ5LjksMzEuMywyMDAuNUw1OC4xLDE3OC4xeiIvPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTkuNiw1MS44YzE4LTYuNywzNy44LTYuOCw1NS45LTAuMkwxNzMsMjEuNGMtMjktMTIuMy02MS44LTEyLjItOTAuOCwwLjNMOTkuNiw1MS44eiIvPgo8cGF0aCBmaWxsPSIjNkFDN0I5IiBkPSJNMTk3LjEsMzUuM2wtMTcuNSwzMC4yYzE0LjgsMTIuMywyNC43LDI5LjUsMjcuOSw0OC41aDM0LjlDMjM4LjcsODIuNywyMjIuNCw1NC4yLDE5Ny4xLDM1LjN6Ii8+CjxwYXRoIGZpbGw9IiNCRjlDQzkiIGQ9Ik0yMDcuNCwxNDEuOWMtNy45LDQzLjktNDkuOSw3My05My44LDY1LjFjLTEzLjgtMi41LTI2LjgtOC42LTM3LjUtMTcuNmwtMjYuOCwyMi40CgljNDYuNiw0My40LDExOS41LDQwLjksMTYyLjktNS43YzE2LjUtMTcuNywyNy00MC4yLDMwLjEtNjQuMkgyMDcuNHoiLz4KPHBhdGggZmlsbD0iI0Q2MUQ1RiIgZD0iTTU4LjEsMTY4LjFDMzguNCwxMzQuMyw0NS44LDkxLjMsNzUuNiw2Nkw1OC4yLDM1LjdDMTAsNzIuMy0xLjcsMTM5LjksMzEuMywxOTAuNUw1OC4xLDE2OC4xeiIvPgo8L3N2Zz4K)
**Markdown Badge Link:**
```
![Assigned badge: gold](https://img.shields.io/badge/D%26I-GOLD-yellow?logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJDSEFPU1NfTG9nbyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmlld0JveD0iMCAwIDI1NSAyNTUiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8cGF0aCBvcGFjaXR5PSIwLjUiIGQ9Ik05OS42LDYxLjhjMTgtNi43LDM3LjgtNi44LDU1LjktMC4yTDE3MywzMS40Yy0yOS0xMi4zLTYxLjgtMTIuMi05MC44LDAuM0w5OS42LDYxLjh6Ii8+CjxwYXRoIG9wYWNpdHk9IjAuNSIgZD0iTTE5Ny4xLDQ1LjNsLTE3LjUsMzAuMmMxNC44LDEyLjMsMjQuNywyOS41LDI3LjksNDguNWgzNC45QzIzOC43LDkyLjcsMjIyLjQsNjQuMiwxOTcuMSw0NS4zeiIvPgo8cGF0aCBvcGFjaXR5PSIwLjUiIGQ9Ik0yMDcuNCwxNTEuOWMtNy45LDQzLjktNDkuOSw3My05My44LDY1LjFjLTEzLjgtMi41LTI2LjgtOC42LTM3LjUtMTcuNmwtMjYuOCwyMi40CgljNDYuNiw0My40LDExOS41LDQwLjksMTYyLjktNS43YzE2LjUtMTcuNywyNy00MC4yLDMwLjEtNjQuMkgyMDcuNHoiLz4KPHBhdGggb3BhY2l0eT0iMC41IiBkPSJNNTguMSwxNzguMUMzOC40LDE0NC4zLDQ1LjgsMTAxLjMsNzUuNiw3Nkw1OC4yLDQ1LjdDMTAsODIuMy0xLjcsMTQ5LjksMzEuMywyMDAuNUw1OC4xLDE3OC4xeiIvPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTkuNiw1MS44YzE4LTYuNywzNy44LTYuOCw1NS45LTAuMkwxNzMsMjEuNGMtMjktMTIuMy02MS44LTEyLjItOTAuOCwwLjNMOTkuNiw1MS44eiIvPgo8cGF0aCBmaWxsPSIjNkFDN0I5IiBkPSJNMTk3LjEsMzUuM2wtMTcuNSwzMC4yYzE0LjgsMTIuMywyNC43LDI5LjUsMjcuOSw0OC41aDM0LjlDMjM4LjcsODIuNywyMjIuNCw1NC4yLDE5Ny4xLDM1LjN6Ii8+CjxwYXRoIGZpbGw9IiNCRjlDQzkiIGQ9Ik0yMDcuNCwxNDEuOWMtNy45LDQzLjktNDkuOSw3My05My44LDY1LjFjLTEzLjgtMi41LTI2LjgtOC42LTM3LjUtMTcuNmwtMjYuOCwyMi40CgljNDYuNiw0My40LDExOS41LDQwLjksMTYyLjktNS43YzE2LjUtMTcuNywyNy00MC4yLDMwLjEtNjQuMkgyMDcuNHoiLz4KPHBhdGggZmlsbD0iI0Q2MUQ1RiIgZD0iTTU4LjEsMTY4LjFDMzguNCwxMzQuMyw0NS44LDkxLjMsNzUuNiw2Nkw1OC4yLDM1LjdDMTAsNzIuMy0xLjcsMTM5LjksMzEuMywxOTAuNUw1OC4xLDE2OC4xeiIvPgo8L3N2Zz4K)
```
**HTML Badge Link:**
```
<img src='https://img.shields.io/badge/D%26I-GOLD-yellow?logo=data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJDSEFPU1NfTG9nbyIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIiB4bWxuczp4bGluaz0iaHR0cDovL3d3dy53My5vcmcvMTk5OS94bGluayIgdmlld0JveD0iMCAwIDI1NSAyNTUiIHhtbDpzcGFjZT0icHJlc2VydmUiPgo8cGF0aCBvcGFjaXR5PSIwLjUiIGQ9Ik05OS42LDYxLjhjMTgtNi43LDM3LjgtNi44LDU1LjktMC4yTDE3MywzMS40Yy0yOS0xMi4zLTYxLjgtMTIuMi05MC44LDAuM0w5OS42LDYxLjh6Ii8+CjxwYXRoIG9wYWNpdHk9IjAuNSIgZD0iTTE5Ny4xLDQ1LjNsLTE3LjUsMzAuMmMxNC44LDEyLjMsMjQuNywyOS41LDI3LjksNDguNWgzNC45QzIzOC43LDkyLjcsMjIyLjQsNjQuMiwxOTcuMSw0NS4zeiIvPgo8cGF0aCBvcGFjaXR5PSIwLjUiIGQ9Ik0yMDcuNCwxNTEuOWMtNy45LDQzLjktNDkuOSw3My05My44LDY1LjFjLTEzLjgtMi41LTI2LjgtOC42LTM3LjUtMTcuNmwtMjYuOCwyMi40CgljNDYuNiw0My40LDExOS41LDQwLjksMTYyLjktNS43YzE2LjUtMTcuNywyNy00MC4yLDMwLjEtNjQuMkgyMDcuNHoiLz4KPHBhdGggb3BhY2l0eT0iMC41IiBkPSJNNTguMSwxNzguMUMzOC40LDE0NC4zLDQ1LjgsMTAxLjMsNzUuNiw3Nkw1OC4yLDQ1LjdDMTAsODIuMy0xLjcsMTQ5LjksMzEuMywyMDAuNUw1OC4xLDE3OC4xeiIvPgo8cGF0aCBmaWxsPSIjMUM5QkQ2IiBkPSJNOTkuNiw1MS44YzE4LTYuNywzNy44LTYuOCw1NS45LTAuMkwxNzMsMjEuNGMtMjktMTIuMy02MS44LTEyLjItOTAuOCwwLjNMOTkuNiw1MS44eiIvPgo8cGF0aCBmaWxsPSIjNkFDN0I5IiBkPSJNMTk3LjEsMzUuM2wtMTcuNSwzMC4yYzE0LjgsMTIuMywyNC43LDI5LjUsMjcuOSw0OC41aDM0LjlDMjM4LjcsODIuNywyMjIuNCw1NC4yLDE5Ny4xLDM1LjN6Ii8+CjxwYXRoIGZpbGw9IiNCRjlDQzkiIGQ9Ik0yMDcuNCwxNDEuOWMtNy45LDQzLjktNDkuOSw3My05My44LDY1LjFjLTEzLjgtMi41LTI2LjgtOC42LTM3LjUtMTcuNmwtMjYuOCwyMi40CgljNDYuNiw0My40LDExOS41LDQwLjksMTYyLjktNS43YzE2LjUtMTcuNywyNy00MC4yLDMwLjEtNjQuMkgyMDcuNHoiLz4KPHBhdGggZmlsbD0iI0Q2MUQ1RiIgZD0iTTU4LjEsMTY4LjFDMzguNCwxMzQuMyw0NS44LDkxLjMsNzUuNiw2Nkw1OC4yLDM1LjdDMTAsNzIuMy0xLjcsMTM5LjksMzEuMywxOTAuNUw1OC4xLDE2OC4xeiIvPgo8L3N2Zz4K' alt='D&I Badging badge state: gold'/>
```
