### ISSUE TITLE
[Virtual Event] cdCon

### ISSUE THREAD

**Issue by RachelBraunLF** [badging/event-diversity-and-inclusion#61]
# Virtual Event Submission

## Requirements

- Event Name: cdCon
- Link to the Event Website: https://events.linuxfoundation.org/cdcon/
- Provide verification that you are an event organizer: Event Planner at the Linux Foundation - my manager is Emily Ruf, who is listed as the event contact on Contact us and Code of Conduct. 

## Speaker Demographics

- [ ] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` "Voluntary speaker demographic information is collected during the CFP process and upon registration. Data collected is used only in aggregate form for reporting attendance totals.Voluntary information requested includes: 
-Gender identity
-Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)
-No all-man programs or panels"
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://events.linuxfoundation.org/cdcon/attend/diversity-inclusion/

## Attendee Demographics

- [ ] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` "Voluntary attendee demographic information is collected upon registration. Data collected is used only in aggregate form for reporting attendance totals. Voluntary information requested includes: 
-Gender identity
-Identification with an underrepresented group in technology (race, ethnicity, dis/ability, LGBTQ, etc.)"
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A` https://events.linuxfoundation.org/cdcon/attend/diversity-inclusion/

## Code of Conduct at Event

- [ ] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes, the code of conduct will be posted in the virtual event platform. All attendees are also required to accept the code of conduct during registration for the event. https://events.linuxfoundation.org/cdcon/register/
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/cdcon/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` cdCon is a free event - there are no barriers to entry, and all are encouraged to attend and participate. 
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` cdCon is a free event - there are no barriers to entry, and all are encouraged to attend and participate. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  cdCon is a free event - there are no barriers to entry, and all are encouraged to attend and participate.

**Comment by Nebrethar** [comment]
@djmitche @Ruth-ikegah since you were both reviewers for the most recent review (#60), I am going to reassign this one. That is some crazy luck.

**Comment by tetris4** [comment]
Hi @RachelBraunLF and thank you for caring enough to apply for this badge.

Here are some comments and questions:
- It would be nice to have some more stats on diversity other than gender and the number of countries, but as it is, should be fine.
- Regarding Attendee Inclusivity, do you have any way to ask for feedback after the event about Diversity and Inclusion?
- The strike through text is for items that are not relevant in your case, because the event is taking place online and is open to everyone.      

And here is my checklist:

# Event Review Checklist

## > Initial checks
- [x] Event is about Open Source technolgies and systems.
- [x] Event information is publicly available on a website.
- [x] The Event Code of Conduct is publicly available.
- [x] The applicant is the organizer of the event.

## > Metric based checks
### >> Speaker Demographics and Inclusivity
- [x] **Measuring demographics** - The Event has a process for measuring speaker demographics.
- [x] **Displaying demographics** - The Event displays speaker demographics.

### >> Attendee Demographics and inclusivity
- [x] **Measuring Demographics** - The Event has a process for measuring Attendee demographics.
- [x] **Displaying demographics** - The Event displays attendee demographics.
- [ ] **Attendee Inclusivity** - The Event requests feedback from attendees regarding Diversity & Inclusion.

### >> Code of Conduct at Event
- [x] **Findability** - It is possible to find the Code of Conduct on the Event website.
- [x] **Clarity** - Event Code of Conduct provides a definition of expected behaviour.
- [ ] ~~**Reporting venue** - The event has a venue for reporting violations of the CoC at the event website.~~
- [x] **Support at Event** - The Event Code of Conduct provided information about possible methods to provide support to victims of inappropriate behavior.
- [x] **Enforcement** - The participants in the Event are required to accept the Code of Conduct.

### >> Diversity Access tickets
- [ ] ~~**Availability** - The event provides one or more Diversity Access Tickets.~~
- [ ] ~~**Ticket allocation** - The Event has a process for allocating diversity access tickets.~~
- [ ] ~~**Findability** - The information about Diversity Access Tickets is public.~~

**Comment by Anita-ihuman** [comment]
@RachelBraunLF  please I need to confirm this, does the Event requests feedback from attendees regarding Diversity & Inclusion?

**Comment by RachelBraunLF** [comment]
@Anita-ihuman - hi!
We encourage all attendees to submit ideas and feedback regarding Diversity & Inclusion directly to our SVP and General Manager of Events, Angela Brown. Her email address is public on the cdCon website with the following explanation:
Contact Us With Ideas
If you have ideas on how we can create a more inclusive event, please do not hesitate to let us know. Contact Angela Brown, SVP & General Manager of Events, at angela@linuxfoundation.org.

https://events.linuxfoundation.org/cdcon/attend/diversity-inclusion/

**Comment by tetris4** [comment]
Thank you @RachelBraunLF for the prompt response, I've updated my evaluation accordingly. 

All the best with the event and keep up the good work on D&I!

**Comment by RachelBraunLF** [comment]
Thank you @tetris4 - are there any steps now required from me to keep this moving forward?

**Comment by Nebrethar** [comment]
Hi @RachelBraunLF

> are there any steps now required from me to keep this moving forward?

**I will generate a badge now.** Thanks for doing so much to improve your events and our process 😁

@tetris4 @Anita-ihuman Thanks for keeping up with great communication. Tetris, I will remove your extra checklist to generate the badge, as we only need one.

Thanks, and let me know if I am missing anything here!

**Comment by Nebrethar** [comment]
@RachelBraunLF Congratulations on another D&I Gold Badge - This time for cdCon! 

I'm really glad you've submitted these events. It shows that you and your event organizing team care about Diversity & Inclusion at your events.

As soon as you confirm this badge is OK with you we will go ahead and award it. Please let us know if you need anything.

**Comment by RachelBraunLF** [comment]
Thank you @Nebrethar - Confirming the badge is great!
Thank you also to @tetris4 and @Anita-ihuman for your review of my submission.
I am excited that we have another event that can showcase our Gold badge and continue to nurture our D&I initiatives!

**Comment by Nebrethar** [comment]
Sounds good 😁 You can find your badge images here, with markdown links below:

SVG: https://svgur.com/s/TX5

PNG:
![image](https://user-images.githubusercontent.com/34951354/106024237-31609300-608d-11eb-9bae-7bd8af48a27c.png)
