### ISSUE TITLE
[In-Person Event] RISC-V Summit 2021

### ISSUE THREAD

**Issue by Naomi-Wash** [badging/event-diversity-and-inclusion#93]
# In-Person Event Submission

## Requirements

- Event Name: RISC-V Summit 2021
- Link to the Event Website: https://events.linuxfoundation.org/riscv-summit/
- Provide verification that you are an event organizer: yes

## Speaker Demographics

- [ ] This event commits to Speaker Diversity and Inclusion.
  - `Q` Detail the process for measuring Speaker Demographics.
  - `A` On the Call for Proposals, we include multiple questions to ensure our speakers are diverse. The language is as follows: RISC-V International is committed to a diverse and inclusive community. The following question is asked in an effort to track our progress in increasing diversity at events and will remain confidential. What gender does the primary speaker identify with?* Is the primary speaker a person of color? Which racial/ethnic background(s) does the primary speaker identify with? (check all that apply) Aside from gender, if the co-speaker identifies with an underrepresented minority group in technology, please indicate that group below (ie race/ethnicity, dis/ability, LGBTQ etc). For panels, more than 2 speakers, we also don't allow panels with only men. On the website we also note that we do not accept all-male panels and we encourage speakers to take the Inclusive Speaker Orientation Course.
  - `Q` Provide the link for the page related to Speaker Demographics if available.
  - `A` https://linuxfoundation.smapply.io/prog/risc-v_summit_2021/

## Attendee Demographics

- [ ] This event commits to Attendee Diversity and Inclusion.
  - `Q` Detail the process for measuring Attendee Demographics.
  - `A` On the registration form, we have a list of language and questions that measure attendee demographics. Language and questions are as follows: Do you have a dis/ability that we should be mindful of as we try to accommodate everyone for this event? We want to encourage greater diversity within the open source community, and demographic information helps us achieve that goal. It is collected solely for the purpose of compiling, analyzing and disclosing aggregate statistics regarding diversity of attendance at our events, to help track progress towards meeting our commitment to diversity initiatives. Consent to provide demographic information for the purpose listed above is optional and purely voluntary, and is provided by selecting an option from the drop-down for the corresponding category. Demographic information is considered confidential and private. It will not be shared with others as part of your registration details, nor will it be used to subject you to adverse treatment. It will be used only in aggregate form for reporting attendance totals. Do you identify as a person of color? What gender do you identify with? How old are you?
  - `Q` Provide the link for the page related to Attendee Demographics if available.
  - `A`  You have to register for the event to view those questions: https://www.cvent.com/d/jmq872/4W?ct=f34626fb-147d-492c-81d2-b77ce49232c1

## Code of Conduct at Event

- [ ] This event commits to the Code of Conduct at Event.
  - `Q` Is the code of conduct posted?
  - `A` Yes, it is available on the website and onsite we will have a large sign that states out our Code of Conduct fully.  
  - `Q` Provide a link for the Event Code of Conduct.
  - `A` https://events.linuxfoundation.org/riscv-summit/attend/code-of-conduct/

## Diversity Access Tickets

- [ ] This event commits to the Diversity Access Tickets.
  - `Q` How many different types of diversity access tickets are available for the event?
  - `A` 1
  - `Q` What are the criteria for qualifying for a diversity access ticket?
  - `A` Applicants must be from a traditionally underrepresented and/or marginalized group in the technology and/or open source communities who are unable to attend without some financial assistance. Including, but not limited to: persons identifying as LGBTQIA+, women, persons of color, and/or persons with dis/abilities. 
  - `Q` Provide a link to the page containing information about Diversity Access Tickets.
  - `A`  https://events.linuxfoundation.org/riscv-summit/attend/scholarships/

## Family Friendliness

- [ ] This event commits to Family Friendliness.
  - `Q` Does the Event provide childcare facilities for its attendees and speakers?
  - `A` Due to local COVID-19 restrictions, we unfortunately cannot offer child care services at this event. We will, however, provide a list of local childcare providers to attendees if they email the events inbox. 
  - `Q` What are the other ways that a family-friendly environment is being created in the Event?
  - `A` A nursing room will be provided to aid in the comfort and accessibility for our nursing attendees. The room will be available all days of the event and will be located onsite. 
  - `Q` Provide relevant links related to family friendliness at the Event.
  - `A`  https://events.linuxfoundation.org/riscv-summit/attend/diversity-inclusion/#onsite-resources

**Comment by Nebrethar** [comment]
Thanks for applying to CHAOSS Badging.

Make sure that you have:
  - Read through [Event submission requirements](https://github.com/badging/event-diversity-and-inclusion/blob/master/submission/requirements.md) and [guidelines](https://github.com/badging/event-diversity-and-inclusion/blob/master/submission/guidelines.md).
  - Understood your [role](https://github.com/badging/diversity-and-inclusion/blob/master/roles/applicant.md) as a CHAOSS Badging applicant.

**Comment by Nebrethar** [comment]
# Checklist for @bistaastha 
Thank you for becoming a part of this Event Badging review.

Make sure you have looked into the following documents:
  - [Reviewer guide](https://github.com/badging/diversity-and-inclusion/blob/master/reviewer-guide.md)
  - [Reviewer role](https://github.com/badging/diversity-and-inclusion/blob/master/roles/reviewer.md)
  - [Submission guidelines](https://github.com/badging/event-diversity-and-inclusion/blob/master/submission/guidelines.md)(In order to get familiar with applicant actions)

In order to avoid receiving excessive notifications from this repository, set your subscription status to `Not Watching`.

---
# Event Review Checklist


## > Initial checks

- [ ] Event is about Open Source technolgies and systems.
- [ ] Event information is publicly available on a website.
- [ ] The Event Code of Conduct is publicly available.
- [ ] The applicant is the organizer of the event.

💡 ``` Make sure all the initial checks are marked before proceeding with Metric based checks```

## > Metric based checks

### >> Speaker Demographics and Inclusivity
- [ ] **Measuring Demographics** - The Event has a process for measuring speaker demographics.
- [ ] **Speaker Inclusivity** - The Event requests feedback from speakers regarding Diversity & Inclusion.
  - Ask applicant about the process if information is not openly available.

### >> Attendee Demographics and inclusivity
- [ ] **Measuring Demographics** - The Event has a process for measuring Attendee demographics.
- [ ] **Attendee Inclusivity** - The Event requests feedback from attendees regarding Diversity & Inclusion.
  - Ask applicant about the process if information is not openly available.

### >> Code of Conduct at Event
- [ ] **Findability** - It is possible to find the Code of Conduct on the Event website.
- [ ] **Clarity** - Event Code of Conduct provides a definition of expected behaviour.
- [ ] **Reporting venue** - The event has a venue for reporting violations of the CoC at the event website.
- [ ] **Support at Event** - The Event Code of Conduct provided information about possible methods to provide support to victims of inappropriate behavior.
- [ ] **Enforcement** - The participants in the Event are required to accept the Code of Conduct.
    

### >> Diversity Access tickets
- [ ] **Availability** - The event provides one or more Diversity Access Tickets.
- [ ] **Ticket allocation** - The Event has a process for allocating diversity access tickets.
- [ ] **Findability** - The information about Diversity Access Tickets is public.

### >> Family Friendliness
- [ ] **Availability** - The Event provides one or more services/facilities for families.
- [ ] **Findability** - The information about the family friendly services provided at the Event is easy to find on the website.

**Comment by Nebrethar** [comment]
# Checklist for @Anita-ihuman 
Thank you for becoming a part of this Event Badging review.

Make sure you have looked into the following documents:
  - [Reviewer guide](https://github.com/badging/diversity-and-inclusion/blob/master/reviewer-guide.md)
  - [Reviewer role](https://github.com/badging/diversity-and-inclusion/blob/master/roles/reviewer.md)
  - [Submission guidelines](https://github.com/badging/event-diversity-and-inclusion/blob/master/submission/guidelines.md)(In order to get familiar with applicant actions)

In order to avoid receiving excessive notifications from this repository, set your subscription status to `Not Watching`.

---
# Event Review Checklist


## > Initial checks

- [ ] Event is about Open Source technolgies and systems.
- [ ] Event information is publicly available on a website.
- [ ] The Event Code of Conduct is publicly available.
- [ ] The applicant is the organizer of the event.

💡 ``` Make sure all the initial checks are marked before proceeding with Metric based checks```

## > Metric based checks

### >> Speaker Demographics and Inclusivity
- [ ] **Measuring Demographics** - The Event has a process for measuring speaker demographics.
- [ ] **Speaker Inclusivity** - The Event requests feedback from speakers regarding Diversity & Inclusion.
  - Ask applicant about the process if information is not openly available.

### >> Attendee Demographics and inclusivity
- [ ] **Measuring Demographics** - The Event has a process for measuring Attendee demographics.
- [ ] **Attendee Inclusivity** - The Event requests feedback from attendees regarding Diversity & Inclusion.
  - Ask applicant about the process if information is not openly available.

### >> Code of Conduct at Event
- [ ] **Findability** - It is possible to find the Code of Conduct on the Event website.
- [ ] **Clarity** - Event Code of Conduct provides a definition of expected behaviour.
- [ ] **Reporting venue** - The event has a venue for reporting violations of the CoC at the event website.
- [ ] **Support at Event** - The Event Code of Conduct provided information about possible methods to provide support to victims of inappropriate behavior.
- [ ] **Enforcement** - The participants in the Event are required to accept the Code of Conduct.
    

### >> Diversity Access tickets
- [ ] **Availability** - The event provides one or more Diversity Access Tickets.
- [ ] **Ticket allocation** - The Event has a process for allocating diversity access tickets.
- [ ] **Findability** - The information about Diversity Access Tickets is public.

### >> Family Friendliness
- [ ] **Availability** - The Event provides one or more services/facilities for families.
- [ ] **Findability** - The information about the family friendly services provided at the Event is easy to find on the website.

**Comment by Nebrethar** [comment]
Note to reviewers: Please use your discretion in whether Family Friendliness is relevant here. If you decide it is not a relevant metric here, feel free to remove it from your own checklist.

**Comment by Anita-ihuman** [comment]
Hello @Naomi-Wash,  
Thanks for applying once again for a D&I badge, it's awesome to see we now have in-person conferences!
- Noticed that the Family-friendly services are clearly stated on the website, if there is an existing resource that provides these details to attendees can you please point it out?
- Do you have a format for collecting feedback from speakers and attendees regarding diversity and inclusivity? can you describe how?
- Also, a suggestion regards measuring the speaker demographics. you can have a page on the site that displays the statistics for attendees and speakers. Here's an example: https://events.linuxfoundation.org/hyperledger-global-forum/attend/diversity-inclusion/#event-demographics

**Comment by Naomi-Wash** [comment]
Hi Anita,

To answer your questions:

   - I think you're referring to the child care section, yes? If so,
   currently there isn't a standing resource that provides childcare
   information to attendees. If an attendee contacts us, we'll provide the
   list of recommended vendors given to us from the local venue.
   - After every event, we send a post-event survey to all attendees that
   asks questions about their experiences. In that survey, we also have an
   open-ended section where they can tell us about any element of the event
   that we could do better on. Also, on our D&I page
   <https://events.linuxfoundation.org/open-source-strategy-forum-london/attend/diversity-inclusion/#contact-us>,
   we have language that specifically states "If you have ideas on how we can
   create a more inclusive event, please do not hesitate to let us know" with
   the contact information for the event manager.
   - This is a new project event for the Linux Foundation, so we don't have
   any historical information to put on a web page. But we'll keep that in
   mind for future events.

I hope this helps, let me know if you have any other questions.

Best.
-Naomi


--
*Naomi Washington*
Event Planner
The Linux Foundation <https://www.linuxfoundation.org/>

T: 1.913.426.3148 (Central Time)
E: ***@***.***

**Comment by bistaastha** [comment]
@Nebrethar I have completed my review.

**Comment by Nebrethar** [comment]
Thank you @Anita-ihuman and @bistaastha for your reviews so far! 🎉

Do you find the Family Friendliness metric relevant to this specific review? I want to make sure I'm not making assumptions about it.

**Comment by Anita-ihuman** [comment]
Yes @Nebrethar, I think while we looking at Diversity & Inclusion, welfare of the speaker/attendees should be a concern too.

**Comment by bistaastha** [comment]
I feel that the Family Friendly metric checks are relevant, as:
a) They make it clear what the event has as a family-friendly service and
what it does not, and how they plan to help out with other aspects.
b) The information is available on the website.

**Comment by Nebrethar** [comment]
Thanks @bistaastha @Anita-ihuman for clarifying. @Naomi-Wash I am going to generate your badge level 🎉 Please let me know whether you accept the DEI badge on behalf of the RISC-V Summit!

**Comment by Naomi-Wash** [comment]
Thank you all! I enjoy applying for these badges. I accept the badge for
RISC-V Summit.

Best,
-Naomi


--
*Naomi Washington*
Event Planner
The Linux Foundation <https://www.linuxfoundation.org/>

T: 1.913.426.3148 (Central Time)
E: ***@***.***

**Comment by Nebrethar** [comment]
Thanks @Naomi-Wash 😁 I also just realized I gave the event a lower score than it earned. I just corrected it 84 -> 93.

...the bot should be back online later today... Thanks 😅
